server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mrKyleWang/config-repo-kylewang
  application:
    name: microservice-config-server-eureka

eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}


