spring:
  application:
    name: eureka2

server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/,http://user:password@localhost:8763/eureka/

security:
  basic:
    enabled: true
  user:
    name: user
    password: password
